# Generated by Django 2.1.7 on 2019-03-18 07:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(default=0, null=True, verbose_name='Parent Category')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug')),
                ('lft', models.IntegerField(default=0, null=True, verbose_name='Lft')),
                ('rgt', models.IntegerField(default=0, null=True, verbose_name='Rgt')),
                ('depth', models.IntegerField(default=0, null=True, verbose_name='Depth')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country Code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
            ],
            options={
                'db_table': 'ref_countries',
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('iso', models.CharField(blank=True, max_length=50, null=True, verbose_name='ISO')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Value')),
                ('default', models.IntegerField(default=0, verbose_name='Default')),
            ],
            options={
                'db_table': 'ref_currencies',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='District Code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
            ],
            options={
                'db_table': 'ref_districts',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Province Code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='references.Countries')),
            ],
            options={
                'db_table': 'ref_provinces',
            },
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, verbose_name='Value')),
            ],
            options={
                'db_table': 'ref_taxes',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='province', to='references.Provinces'),
        ),
    ]
